@startuml tyreStrategySimDiagram
skinparam classAttributeIconSize 0
skinparam monochrome true

class TrackEnvironment <<Singleton>> {
  - float trackTemperature
  - float timeOfDayHours
  - bool isNightTime
  - float currentWetness
  - int rainIntensity
  - int remainingRainLaps
  - TrackEnvironment()
  
  + static TrackEnvironment& getInstance()
  + float getTrackTemp()
  + bool checkIsNight()
  + float getCurrentWetness()
  + int getRainIntensity()
  + int getRemainingRainLaps()
  + void setRainLaps(int minRainLaps, int maxRainLaps)
  + void updateWeather()
  + void advanceTime(float hours)
}

abstract class ITyreCompound {
  # float currentWear
  # string compoundName

  + ~ITyrecompound()
  + virtual float calculateGrip(float lapsCompleted) = 0
  + virtual void printStatus() = 0
  + string getName()
  + float getWear()
}

class WetTyre {
  - float waterDisplacementRate

  + float calculateGrip(int lapsCompleted) override
  + void printStatus() override
}

class SlickTyre {
  # float optimalTempWindow
}

class SoftCompound {
  - float blisteringFactor

  + SoftCompound()
  + float calculateGrip(int lapsCompleted) override
  + void printStatus() override
}

class HardCompound {
  - float warmUpTime

  + HardCompound()
  + float calculateGrip(int lapsCompleted) override
  + void printStatus() override
}

class RaceCar {
  - string teamName
  - float fuelTankCapacity
  - float currentFuel
  - int currentStintLaps
  - ITyreCompound* currentTyres
  - vector<ITyreCompound*> usedTyres
  - bool isDNF
  - int lapsCompleted
  - float totalRaceTime

  + RaceCar()
  + ~RaceCar()
  + std::string getTeamName()
  + float getFuelTankCapacity()
  + float getCurrentFuel()
  + int getCurrentStintLaps()
  + ITyreCompound *getCurrentTyres()
  + std::vector<ITyreCompound *> getUsedTyres()
  + bool getIsDNF()
  + int getLapsCompleted()
  + float getTotalRaceTime()
  + void executePitStop(float fuelAmount)
  + void executePitStop(float fuelAmount, ITyreCompound* newTyres)
  + float completeLap()
}

class EnduranceSimulation {
  - vector<RaceCar*> grid
  - float currentRaceHours
  - float totalRaceHours
  
  + EnduranceSimulation()
  + ~EnduranceSimulation()
  + void start24hRace()
}

ITyreCompound <|-- WetTyre
ITyreCompound <|-- SlickTyre
SlickTyre <|-- SoftCompound
SlickTyre <|-- HardCompound

RaceCar o-- ITyreCompound : "Polymorfní kompozice"
EnduranceSimulation *-- RaceCar : "Kompozice (obsahuje grid)"
TrackEnvironment <-- ITyreCompound : "Závislost (čte teplotu)"
TrackEnvironment <-- EnduranceSimulation : "Závislost (řídí 24h čas)"
@enduml